permalink:   blog/:title/
title_pre:   With
title:       Ken Powers
title_post:  Comes Ken Responsibility
tagline:     With Ken Powers Comes Ken Responsibility
url:         http://knpw.rs
baseurl:     ''
author:
  name:      Ken Powers
  full_name: Kenneth Powers
  email:     ken@kenpowers.net
  github:    https://github.com/knpwrs
  twitter:   https://twitter.com/knpwrs
  linkedin:  https://www.linkedin.com/profile/view?id=168773387
